### ISSUE TITLE
branches

### ISSUE THREAD

**Issue by vanackerglenn** [rish-16/sight#2]
Hi, we spoke earlier today on reddit. I cloned the repo, and i'm going to take a look. Not sure how you handle things tho. don't you use branches? You could potentially destroy a lot of the work you've done already. I suggest making a develop branch, from the master branch, and base everything on that. that way, every once in a while, you could release to that one if you're sure about the changes.

**Comment by rish-16** [comment]
Sounds good. Thanks for the suggestion. Let me create a `development` branch for experiments.

**Comment by rish-16** [comment]
Alright, I've created a development branch for quick experimentation and prototyping.
