### ISSUE TITLE
Face Detection and Recognition

### ISSUE THREAD

**Issue by DesiKeki** [rish-16/sight#7]
Hi Rishabh,

Great job you have done! This kind of a package will be definitely useful for many computer vision users like me. In the roadmap however, I could not see any plan to implement Face Detection and Recognition using models like `facenet ` or `deepface ` etc. 
I feel that these features will definitely find a very good fit in a computer vision wrapper like sightseer. It will be good to see a plan for the same.

Regards
Keki :)

**Comment by rish-16** [comment]
Yes, of course! Let me add that to the Roadmap. Would be an amazing add-on to the `sightseer.zoo` model family. 
Cheers!

**Comment by DesiKeki** [comment]
Great! Lets make sightseer a wonderful utility.
